sudo: required

language: c

notifications:
  email: false

env:
  global:
      - DOCKER_VERSION=1.10.1-0~trusty

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.[0-9]+/

services:
  - docker

install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - pip install --user cpp-coveralls

script:
  - docker network create --subnet=172.26.0.0/24 test
  - docker run -d --net test --ip 172.26.0.2 --name zookeeper wurstmeister/zookeeper
  - docker run -d --net test --ip 172.26.0.3 --name kafka -e KAFKA_ADVERTISED_HOST_NAME="172.26.0.3" -e KAFKA_ADVERTISED_PORT="9092" -e KAFKA_ZOOKEEPER_CONNECT="172.26.0.2:2181" -v /var/run/docker.sock:/var/run/docker.sock wurstmeister/kafka
  - docker run -v $(pwd):/app redborder/build-dockerfiles:n2kafka ./configure
  - docker run -v $(pwd):/app redborder/build-dockerfiles:n2kafka make
  - docker run -v $(pwd):/app -e CFLAGS=-w --link kafka --net test redborder/build-dockerfiles:n2kafka make tests

after_success:
  - docker run -v $(pwd):/app redborder/build-dockerfiles:n2kafka make clean
  - docker run -v $(pwd):/app redborder/build-dockerfiles:n2kafka ./configure --enable-coverage
  - docker run -v $(pwd):/app -e CFLAGS=-w --link kafka --net test redborder/build-dockerfiles:n2kafka make coverage
  - docker run -v $(pwd):/app redborder/build-dockerfiles:n2kafka lcov --remove tests/coverage.info 'tests/*' '/usr/*' --output-file tests/coverage.info
  - docker run -v $(pwd):/app redborder/build-dockerfiles:n2kafka lcov --list tests/coverage.info
  - coveralls --exclude /usr/lib --exclude tests --gcov-options '\-lp'

before_deploy:
  - tar -cvzf n2kafka-${TRAVIS_TAG}.tar.gz n2kafka

deploy:
  provider: releases
  api_key:
    secure: dTyNSU5oSYX9mc5u25b3Hxzui0nNp88z1IVaxAK7A1qROld3S9GT4PbM5jzM/kYrHrpbzGeV7NUzh/WyAorgtYa2W5waJyTA1WhTx2Vn2NUOcm5TZ1KiOHxK05zeIsTMVjzEIRXGj1xsoQ1f9dwzlBh1cMx5jSDk4E3+B/YKFgQ=
  file: n2kafka-${TRAVIS_TAG}.tar.gz
  on:
    tags: true
